### ISSUE TITLE
Module is no longer loading

### ISSUE THREAD

**Issue by ngdemigod** [parnic/MMM-Ecobee#2]
The module is stuck in a loading state. Can you please take a look at this.
![image](https://github.com/parnic/MMM-Ecobee/assets/19669241/560c3596-1647-4c90-8087-e204e43fbad5)

**Comment by iceemike** [comment]
I'm also having this issue. Does it need a new app key?

**Comment by parnic** [comment]
It did back when this was reported, but I made a new one. Are you on the latest commit?
