### ISSUE TITLE
Ecobee app integration with MM will break after restarting MM

### ISSUE THREAD

**Issue by monukoshy** [parnic/MMM-Ecobee#3]
So anytime I am adding or modifying the config.js file in MM the app integration breaks, and the module reverts back to this message.
Its then I have to delete the app in ecobee and then create a new app with the new authorization code. How do i overcome this.

![image](https://github.com/parnic/MMM-Ecobee/assets/18563125/b5d1ee5e-0fc3-4eae-898a-ca78f3504235)

**Comment by parnic** [comment]
I've seen that a couple of times locally but hadn't connected it to changing config.js. I am not sure why this happens, but will try and find some time to look into it. If you figure it out, I'd be happy to accept a PR.

**Comment by monukoshy** [comment]
This issue is similar to the one that happened with the previous version of MMM-Ecobee as stated here in this post.
https://github.com/fabbr/MMM-Ecobee/issues/1
Its exactly the same issue. Each time MM reboots or config.js file is edited, MM will generate a new auth token.

**Comment by parnic** [comment]
Check this out with b32b8fd02b44b5a029ac7c59d2ef217f65ca61e7. I'm not sure if that will fully fix it or not, but I've been running with that change locally for a while now and haven't seen a re-auth prompt. The bug in the original module had changes made for it, even though it's not marked as resolved, and I've done more toward it since forking.

**Comment by monukoshy** [comment]
Thanks for looking into this with urgency. Looks like you made changes to the node_helper.js file. I downloaded the new file and replaced it with the old one, still did not work. I then deleted the MMM-Ecobee module folder, and redownloaded it using git clone and ran npm run still no fun. Each time Config.js is reloaded there is a new auth code.

**Comment by parnic** [comment]
I'm not seeing that problem. Can you confirm that the user running MagicMirror has write access to the modules/MMM-Ecobee folder? There should be a tokens.json file in that directory that the module uses to track these tokens.

**Comment by monukoshy** [comment]
you are right, the user is mm, and all the items are owned by root, and mm is not able to write to anything under MMM-Ecobee folder, i have to use sudo each time if i need to make change,. what do u suggest i should do? change the ownership of MMM-Ecobee to from root to mm using chown cmmand?

**Comment by monukoshy** [comment]
and there is no token.json file in the MMM-Ecobee folder

**Comment by parnic** [comment]
You can create an empty file named `tokens.json` in the MMM-Ecobee module directory and chown it to the user running MM, that should be enough.

**Comment by monukoshy** [comment]
PERFECT!!! Thank you so much!! This resolve this issue. Thanks again for looking into this. This issue can be marked as closed.

**Comment by parnic** [comment]
I'll push an update to the readme to explain this.
